modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="postmortem"
version="1.0.2"
displayName="Postmortem"
displayURL="https://ko-fi.com/autumnly"
logoFile="logo.png"
credits="Made by Autumnly24, Inspired by Requiem"
authors="Autumn"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.postmortem]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.postmortem]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.postmortem]]
    modId="pehkui"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.postmortem]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration